<?php
namespace frontend\components;
use yii\base\ActionFilter;
use yii\web\HttpException;

class AccessFilter extends ActionFilter
{
    public function beforeAction($action)
    {

            //判断是否登录，未登录跳转到登录页面
            if(\Yii::$app->user->isGuest){
                return $action->controller->redirect(\Yii::$app->user->loginUrl);
            }
//            //没有权限，抛出403
//            throw new HttpException(403,'对不起，你没有权限访问当前页面');


        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
