<?php

namespace frontend\models;

use Yii;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "member".
 *
 * @property integer $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string $email
 * @property string $tel
 * @property integer $last_login_time
 * @property integer $last_login_ip
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 */
class Member extends \yii\db\ActiveRecord implements IdentityInterface
{

    public $password;//明文密码
    public $cfirmPassword;//确认密码
    public $code;//验证码
//    public $smsCode;//手机验证码


//定义场景
const SCENARIO_REGISTER = 'register';
const SCENARIO_API_REGISTER = 'api_register';
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'member';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username','password','cfirmPassword'], 'required'],
            [['last_login_time', 'last_login_ip', 'status', 'created_at', 'updated_at'], 'integer'],
            [['username'], 'string', 'max' => 50],
            [['auth_key'], 'string', 'max' => 32],
            [['password_hash', 'email'], 'string', 'max' => 100],
            [['tel'], 'string', 'max' => 11],
            ['code','captcha','on'=>self::SCENARIO_REGISTER],
            ['code','captcha','on'=>self::SCENARIO_API_REGISTER,'captchaAction'=>'api/captcha'],
            ['cfirmPassword','compare','compareAttribute'=>'password','message'=>'两次密码必须一致'],
//            ['smsCode','validateSms']

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => '用户名：',
            'auth_key' => 'Auth Key',
            'password_hash' => 'Password Hash',
            'password'=>'密码：',
            'cfirmPassword'=>'确认密码：',
            'email' => '邮箱：',
            'tel' => '手机号码：',
            'code'=>'验证码：',
            'last_login_time' => 'Last Login Time',
            'last_login_ip' => 'Last Login Ip',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
//            'smsCode'=>'手机验证码：'
        ];
    }

    //验证手机验证码
    public function validateSms(){
        //验证缓存里面有没有这个手机号码
        $value = Yii::$app->cache->get('tel_'.$this->tel);
        if( !$value || $this->smsCode != $value){
            $this->addError('smsCode','验证码不正确');
        }

    }

    //保存前执行操作 1-加密密码 2-添加时间等
    public function beforeSave($insert)
    {
        if($insert){
            $this->created_at = time();
            $this->password_hash = Yii::$app->security->generatePasswordHash($this->password); //加密密码
            $this->auth_key = Yii::$app->security->generateRandomString();//生成令牌
        }else{
            //修改
            $this->updated_at = time();
            $this->password_hash = Yii::$app->security->generatePasswordHash($this->password); //加密密码
            $this->auth_key = Yii::$app->security->generateRandomString();//生成令牌
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    /**
     * Finds an identity by the given ID.
     * @param string|int $id the ID to be looked for
     * @return IdentityInterface the identity object that matches the given ID.
     * Null should be returned if such an identity cannot be found
     * or the identity is not in an active state (disabled, deleted, etc.)
     */
    public static function findIdentity($id)
    {
        return self::findOne(['id'=>$id]);
    }

    /**
     * Finds an identity by the given token.
     * @param mixed $token the token to be looked for
     * @param mixed $type the type of the token. The value of this parameter depends on the implementation.
     * For example, [[\yii\filters\auth\HttpBearerAuth]] will set this parameter to be `yii\filters\auth\HttpBearerAuth`.
     * @return IdentityInterface the identity object that matches the given token.
     * Null should be returned if such an identity cannot be found
     * or the identity is not in an active state (disabled, deleted, etc.)
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        // TODO: Implement findIdentityByAccessToken() method.
    }

    /**
     * Returns an ID that can uniquely identify a user identity.
     * @return string|int an ID that uniquely identifies a user identity.
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns a key that can be used to check the validity of a given identity ID.
     *
     * The key should be unique for each individual user, and should be persistent
     * so that it can be used to check the validity of the user identity.
     *
     * The space of such keys should be big enough to defeat potential identity attacks.
     *
     * This is required if [[User::enableAutoLogin]] is enabled.
     * @return string a key that is used to check the validity of a given identity ID.
     * @see validateAuthKey()
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * Validates the given auth key.
     *
     * This is required if [[User::enableAutoLogin]] is enabled.
     * @param string $authKey the given auth key
     * @return bool whether the given auth key is valid.
     * @see getAuthKey()
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() == $authKey;
    }
}
