<?php
namespace frontend\widgets;

use backend\models\GoodsCategory;
use yii\base\Widget;

class CategoryWidget extends Widget{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //redis存放商品分类
/*        $redis = new \Redis(); //实例化redis
        $redis->connect(); //连接redis
        $category_html = $redis->get('category_html'); //查询key对应value
        if($category_html == null){   //为空则生成分类列表重新保存至redis*/

            $categories = GoodsCategory::find()->where(['parent_id'=>0])->all();
            $category_html = $this->renderFile('@app/widgets/view/category.php',['categories'=>$categories]);


        /*    $redis->set('category_html',$category_html);
        }*/

        return $category_html;

    }


}