<?php
/**
 * Created by PhpStorm.
 * User: lixun
 * Date: 2017/6/18
 * Time: 23:05
 */

namespace backend\components;


use yii\base\ActionFilter;
use yii\web\HttpException;

class RbacFilter extends ActionFilter
{
    public function beforeAction($action)
    {

        $user = \Yii::$app->user;

        if(!$user->can($action->uniqueId)){ //判断用户是否有当前操作的权限

            if($user->isGuest){
                return $action->controller->redirect(\Yii::$app->user->loginUrl);
            }
            throw new HttpException(403,'对不起，你没有操作权限');
            return false;

        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}